import React, { useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useMutation, useQuery } from '@tanstack/react-query';
import { MessageCircle, Search, UserPlus } from 'lucide-react-native';
import { router } from 'expo-router';
import { createConversation, searchPosts, searchUsers, sendFriendRequest, unwrapList } from '@/lib/api';
import { Avatar } from '@/components/avatar';
import { Card } from '@/components/ui';
import { PostCard } from '@/components/post-card';
import { colors, spacing } from '@/theme';
import { showApiError, showSuccess } from '@/state/ui-store';
import type { User } from '@/types';

export default function ExploreScreen() {
  const [query, setQuery] = useState('');
  const [mode, setMode] = useState<'people' | 'posts'>('people');
  const enabled = query.trim().length >= 2;
  const people = useQuery({ queryKey: ['search', 'people', query], queryFn: () => searchUsers(query.trim()), enabled: enabled && mode === 'people' });
  const posts = useQuery({ queryKey: ['search', 'posts', query], queryFn: () => searchPosts(query.trim()), enabled: enabled && mode === 'posts' });
  const request = useMutation({ mutationFn: sendFriendRequest, onSuccess: () => showSuccess('Request sent', 'They will see your Flow request.'), onError: (e) => showApiError(e, 'Could not send request') });
  const message = useMutation({ mutationFn: (id: number) => createConversation([id]), onSuccess: (conversation) => router.push({ pathname: '/conversation/[id]', params: { id: String(conversation.id), name: conversation.name } }), onError: (e) => showApiError(e, 'Could not start conversation') });
  const users = Array.isArray(people.data) ? people.data : [];
  const postItems = unwrapList(posts.data);
  return <View style={styles.root}><View style={styles.top}><Text style={styles.title}>Explore Flow</Text><Text style={styles.subtitle}>Find classmates and campus conversations.</Text><View style={styles.search}><Search color={colors.muted} size={20} /><TextInput autoCapitalize="none" onChangeText={setQuery} placeholder="Search people or posts" placeholderTextColor={colors.muted} style={styles.searchInput} value={query} /></View><View style={styles.tabs}><Pressable onPress={() => setMode('people')} style={[styles.tab, mode === 'people' && styles.activeTab]}><Text style={[styles.tabText, mode === 'people' && styles.activeTabText]}>People</Text></Pressable><Pressable onPress={() => setMode('posts')} style={[styles.tab, mode === 'posts' && styles.activeTab]}><Text style={[styles.tabText, mode === 'posts' && styles.activeTabText]}>Posts</Text></Pressable></View></View>{mode === 'people' ? <FlatList contentContainerStyle={styles.list} data={users} keyExtractor={(item) => String(item.id || item.user_id)} renderItem={({ item }: { item: User }) => <Card style={styles.person}><Avatar user={item} size={50} /><View style={{ flex: 1 }}><Text style={styles.name}>{[item.first_name, item.last_name].filter(Boolean).join(' ') || item.user_name || item.email}</Text><Text style={styles.meta}>{item.department || item.email}</Text></View><Pressable onPress={() => request.mutate((item.id || item.user_id)!)} style={styles.iconButton}><UserPlus color={colors.primary} size={20} /></Pressable><Pressable onPress={() => message.mutate((item.id || item.user_id)!)} style={styles.iconButton}><MessageCircle color={colors.primary} size={20} /></Pressable></Card>} ItemSeparatorComponent={() => <View style={{ height: 10 }} />} ListEmptyComponent={<Text style={styles.empty}>{enabled ? 'No matching students.' : 'Enter at least two characters.'}</Text>} /> : <FlatList contentContainerStyle={styles.list} data={postItems} keyExtractor={(item) => String(item.id)} renderItem={({ item }) => <PostCard post={item} />} ItemSeparatorComponent={() => <View style={{ height: 10 }} />} ListEmptyComponent={<Text style={styles.empty}>{enabled ? 'No matching posts.' : 'Enter at least two characters.'}</Text>} />}</View>;
}
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.background }, top: { padding: spacing.lg, gap: 10, backgroundColor: '#fff', borderBottomWidth: 1, borderBottomColor: colors.border }, title: { color: colors.text, fontSize: 27, fontWeight: '900' }, subtitle: { color: colors.muted }, search: { minHeight: 48, borderWidth: 1, borderColor: colors.border, borderRadius: 15, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, gap: 10 }, searchInput: { flex: 1, color: colors.text, fontSize: 15 }, tabs: { flexDirection: 'row', backgroundColor: colors.background, borderRadius: 14, padding: 4 }, tab: { flex: 1, alignItems: 'center', paddingVertical: 9, borderRadius: 11 }, activeTab: { backgroundColor: '#fff' }, tabText: { color: colors.muted, fontWeight: '700' }, activeTabText: { color: colors.primary }, list: { padding: spacing.lg, paddingBottom: 40 }, person: { flexDirection: 'row', alignItems: 'center', gap: 10 }, name: { color: colors.text, fontWeight: '800' }, meta: { color: colors.muted, fontSize: 12, marginTop: 3 }, iconButton: { width: 40, height: 40, borderRadius: 13, backgroundColor: '#EEF2FF', alignItems: 'center', justifyContent: 'center' }, empty: { color: colors.muted, textAlign: 'center', paddingTop: 60 } });
